name: kriminalstatistik
services:
  postgresql:
    image: postgres:latest
    container_name: postgres_ws25
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql:ro  # init database

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_ws25
    env_file:
      - .env
    ports:
      - "8080:80"
    depends_on:
      - postgresql
    volumes:
      - ./pgadmin/servers.json:/pgadmin4/servers.json  # server configuration

